#index:
#    path: /
#    controller: App\Controller\DefaultController::index

####### relation entre controlleur et chemin d'acces
Michelin_accueil:
  ## path: /afficher
  path: /guideMichelin
  controller: App\Controller\MichelinController::accueil
